package gui;
import com.placeholder.PlaceHolder;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.JToggleButton;
import negocio.Mesa;
import negocio.Producto;
import datos.Registro;
import javax.swing.JTextArea;
import negocio.Cliente;
import datos.ConsultaBD;
import datos.InsertarBD;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.text.StyledEditorKit;

public class VentanaPrincipal extends javax.swing.JFrame {
    
    int numMesa;
    int total;

    public int getNumMesa() {
        return numMesa;
    }

    public void setNumMesa(int numMesa) {
        this.numMesa = numMesa;
    }
    
    ArrayList<Cliente> listaCliente;
    ArrayList<Mesa> listaMesa;
    ArrayList<Producto> listaProducto;
    
    //LISTADO DE MESAS CON SUS PRODUCTOS ASOCIADOS
    public List<Registro> registro = new ArrayList<Registro>();
    //LISTADO DE CLIENTES
    public List<Cliente> clientes = new ArrayList<Cliente>();
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        //CREA PLACEHOLDER PARA BUSQUEDA DE CLIENTE DELIVERY
        PlaceHolder p2;
        p2 = new PlaceHolder(txtBusquedaDelivery, "Ingrese nombre de cliente a buscar");
        txtBusquedaDelivery.setEnabled(false);
        btnBuscarDelivery.setEnabled(false);
        btnDelivery.setEnabled(true);
    }

    public VentanaPrincipal(Cliente cliente) {
        initComponents();
        //CREA PLACEHOLDER PARA BUSQUEDA DE CLIENTE DELIVERY
        PlaceHolder p2;
        p2 = new PlaceHolder(txtBusquedaDelivery, "Ingrese nombre de cliente a buscar");
        txtBusquedaDelivery.setEnabled(false);
        btnBuscarDelivery.setEnabled(false);
        btnDelivery.setEnabled(false);
        clientes.add(cliente);
        btnM1.setEnabled(false);
        btnM2.setEnabled(false);
        btnM3.setEnabled(false);
        btnM4.setEnabled(false);
        btnM5.setEnabled(false);
        btnM6.setEnabled(false);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnM1 = new javax.swing.JToggleButton();
        btnM2 = new javax.swing.JToggleButton();
        btnM3 = new javax.swing.JToggleButton();
        btnM6 = new javax.swing.JToggleButton();
        btnM5 = new javax.swing.JToggleButton();
        btnM4 = new javax.swing.JToggleButton();
        btnDelivery = new javax.swing.JToggleButton();
        cbxCamaron = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        cbxEmpanadas = new javax.swing.JCheckBox();
        cbxPalta = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        cbxCarne = new javax.swing.JCheckBox();
        cbxCerdo = new javax.swing.JCheckBox();
        cbxPescado = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        cbxArroz = new javax.swing.JCheckBox();
        cbxPure = new javax.swing.JCheckBox();
        cbxEnsalada = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        cbxHelado = new javax.swing.JCheckBox();
        cbxTuti = new javax.swing.JCheckBox();
        cbxLeche = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        cbxGaseosa = new javax.swing.JCheckBox();
        cbxVino = new javax.swing.JCheckBox();
        cbxJugo = new javax.swing.JCheckBox();
        btnAceptarPedido = new javax.swing.JButton();
        btnCancelarPedido = new javax.swing.JButton();
        btnAgregarPlato = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaPedido = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnPagarMesa1 = new javax.swing.JToggleButton();
        btnPagarMesa2 = new javax.swing.JToggleButton();
        btnPagarMesa3 = new javax.swing.JToggleButton();
        btnPagarMesa4 = new javax.swing.JToggleButton();
        btnPagarMesa5 = new javax.swing.JToggleButton();
        btnPagarMesa6 = new javax.swing.JToggleButton();
        btnPagoDelivery = new javax.swing.JToggleButton();
        txtBusquedaDelivery = new javax.swing.JTextField();
        btnBuscarDelivery = new javax.swing.JButton();
        btnPagarPedido = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaPagar = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Restaurant Donde El Pepe");
        setMaximumSize(new java.awt.Dimension(620, 800));
        setPreferredSize(new java.awt.Dimension(800, 640));
        setResizable(false);
        setSize(new java.awt.Dimension(620, 800));

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(800, 620));

        jPanel1.setPreferredSize(new java.awt.Dimension(700, 800));
        jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel1FocusGained(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/restaurante.png"))); // NOI18N
        jLabel1.setText("Seleccione una mesa");

        buttonGroup1.add(btnM1);
        btnM1.setText("1");
        btnM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnM1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnM2);
        btnM2.setText("2");
        btnM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnM2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnM3);
        btnM3.setText("3");
        btnM3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnM3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnM6);
        btnM6.setText("6");
        btnM6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnM6ActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnM5);
        btnM5.setText("5");
        btnM5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnM5ActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnM4);
        btnM4.setText("4");
        btnM4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnM4ActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnDelivery);
        btnDelivery.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icon delivery.png"))); // NOI18N
        btnDelivery.setText("  Delivery");
        btnDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeliveryActionPerformed(evt);
            }
        });

        buttonGroup2.add(cbxCamaron);
        cbxCamaron.setText("Camarón");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Entrada");

        buttonGroup2.add(cbxEmpanadas);
        cbxEmpanadas.setText("Empanadas");

        buttonGroup2.add(cbxPalta);
        cbxPalta.setText("Palta Reina");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Fondo Principal");

        buttonGroup3.add(cbxCarne);
        cbxCarne.setText("Carne");

        buttonGroup3.add(cbxCerdo);
        cbxCerdo.setText("Cerdo");

        buttonGroup3.add(cbxPescado);
        cbxPescado.setText("Pescado");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Acompañamiento");

        buttonGroup4.add(cbxArroz);
        cbxArroz.setText("Arroz");

        buttonGroup4.add(cbxPure);
        cbxPure.setText("Puré");

        buttonGroup4.add(cbxEnsalada);
        cbxEnsalada.setText("Ensalada");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Postre");

        buttonGroup5.add(cbxHelado);
        cbxHelado.setText("Helado");

        buttonGroup5.add(cbxTuti);
        cbxTuti.setText("Tutifruti");

        buttonGroup5.add(cbxLeche);
        cbxLeche.setText("Leche Asada");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Bebestible");

        buttonGroup6.add(cbxGaseosa);
        cbxGaseosa.setText("Gaseosa");

        buttonGroup6.add(cbxVino);
        cbxVino.setText("Vino");

        buttonGroup6.add(cbxJugo);
        cbxJugo.setText("Jugo");

        btnAceptarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/aceptar.png"))); // NOI18N
        btnAceptarPedido.setText("ACEPTAR");
        btnAceptarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarPedidoActionPerformed(evt);
            }
        });

        btnCancelarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/cancelar.png"))); // NOI18N
        btnCancelarPedido.setText("CANCELAR");
        btnCancelarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPedidoActionPerformed(evt);
            }
        });

        btnAgregarPlato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/mas.png"))); // NOI18N
        btnAgregarPlato.setText("Agregar Plato");
        btnAgregarPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPlatoActionPerformed(evt);
            }
        });

        txaPedido.setEditable(false);
        txaPedido.setColumns(20);
        txaPedido.setRows(5);
        jScrollPane1.setViewportView(txaPedido);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxCamaron)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxCarne)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(107, 107, 107)
                                        .addComponent(cbxCerdo)))
                                .addGap(46, 46, 46)
                                .addComponent(cbxPescado))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(209, 209, 209)
                                .addComponent(cbxJugo))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(107, 107, 107)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(cbxEmpanadas)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(cbxPalta))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(102, 102, 102)
                                            .addComponent(cbxLeche))))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbxArroz)
                                        .addComponent(cbxHelado))
                                    .addGap(40, 40, 40)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(cbxPure)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                                            .addComponent(cbxEnsalada, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(19, 19, 19)
                                                    .addComponent(jLabel6))
                                                .addComponent(jLabel4)
                                                .addComponent(cbxTuti))
                                            .addGap(0, 0, Short.MAX_VALUE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbxGaseosa)
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAgregarPlato)
                                    .addComponent(cbxVino)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnM1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnM2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnM3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnM4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnDelivery, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnM5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnM6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCancelarPedido)
                        .addGap(34, 34, 34)
                        .addComponent(btnAceptarPedido)))
                .addGap(97, 97, 97))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel1)
                .addContainerGap(476, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnM1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnM2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnM3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnM4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnM5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnM6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnDelivery)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxCamaron)
                            .addComponent(cbxEmpanadas)
                            .addComponent(cbxPalta))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxCarne)
                            .addComponent(cbxCerdo)
                            .addComponent(cbxPescado))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxArroz)
                            .addComponent(cbxPure)
                            .addComponent(cbxEnsalada))
                        .addGap(24, 24, 24)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxHelado)
                            .addComponent(cbxTuti)
                            .addComponent(cbxLeche))
                        .addGap(12, 12, 12)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxGaseosa)
                            .addComponent(cbxVino)
                            .addComponent(cbxJugo)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarPlato)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCancelarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAceptarPedido)))
                .addContainerGap(191, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pedido", jPanel1);

        jPanel2.setPreferredSize(new java.awt.Dimension(620, 800));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("Seleccionar una mesa");

        buttonGroup7.add(btnPagarMesa1);
        btnPagarMesa1.setText("1");
        btnPagarMesa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarMesa1ActionPerformed(evt);
            }
        });

        buttonGroup7.add(btnPagarMesa2);
        btnPagarMesa2.setText("2");
        btnPagarMesa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarMesa2ActionPerformed(evt);
            }
        });

        buttonGroup7.add(btnPagarMesa3);
        btnPagarMesa3.setText("3");
        btnPagarMesa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarMesa3ActionPerformed(evt);
            }
        });

        buttonGroup7.add(btnPagarMesa4);
        btnPagarMesa4.setText("4");
        btnPagarMesa4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarMesa4ActionPerformed(evt);
            }
        });

        buttonGroup7.add(btnPagarMesa5);
        btnPagarMesa5.setText("5");
        btnPagarMesa5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarMesa5ActionPerformed(evt);
            }
        });

        buttonGroup7.add(btnPagarMesa6);
        btnPagarMesa6.setText("6");
        btnPagarMesa6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarMesa6ActionPerformed(evt);
            }
        });

        buttonGroup7.add(btnPagoDelivery);
        btnPagoDelivery.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icon delivery.png"))); // NOI18N
        btnPagoDelivery.setText("Delivery");
        btnPagoDelivery.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnPagoDeliveryFocusLost(evt);
            }
        });
        btnPagoDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagoDeliveryActionPerformed(evt);
            }
        });

        btnBuscarDelivery.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/lupa.png"))); // NOI18N
        btnBuscarDelivery.setText("BUSCAR");
        btnBuscarDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarDeliveryActionPerformed(evt);
            }
        });

        btnPagarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/dinero.png"))); // NOI18N
        btnPagarPedido.setText("PAGAR");
        btnPagarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarPedidoActionPerformed(evt);
            }
        });

        txaPagar.setColumns(20);
        txaPagar.setRows(5);
        jScrollPane2.setViewportView(txaPagar);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(283, 283, 283)
                                    .addComponent(btnPagarPedido))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnPagarMesa1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPagarMesa2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPagarMesa3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPagarMesa4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPagarMesa5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPagarMesa6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtBusquedaDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarDelivery)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnPagoDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPagarMesa1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPagarMesa2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPagarMesa3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPagarMesa4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPagarMesa5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPagarMesa6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPagoDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtBusquedaDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btnPagarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(265, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pagar", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //GENERA UN LISTADO DE LOS BOTONES DE LAS MESAS
    private List<JToggleButton> agregarBtn(){
        
        List<JToggleButton> botonesMesas = new ArrayList<JToggleButton>();
        
        botonesMesas.add(btnM1);
        botonesMesas.add(btnM2);
        botonesMesas.add(btnM3);
        botonesMesas.add(btnM4);
        botonesMesas.add(btnM5);
        botonesMesas.add(btnM6);
        
        return botonesMesas;
    }
    
    //GENERA UN LISTADO DE LOS CHECKBOX DE LOS PRODUCTOS
    private List<JCheckBox> agregarCbx(){
        List<JCheckBox> cbxProductos = new ArrayList<JCheckBox>();
        
        cbxProductos.add(cbxCamaron);
        cbxProductos.add(cbxEmpanadas);
        cbxProductos.add(cbxPalta);
        cbxProductos.add(cbxCarne);
        cbxProductos.add(cbxCerdo);
        cbxProductos.add(cbxPescado);
        cbxProductos.add(cbxArroz);
        cbxProductos.add(cbxPure);
        cbxProductos.add(cbxEnsalada);
        cbxProductos.add(cbxHelado);
        cbxProductos.add(cbxTuti);
        cbxProductos.add(cbxLeche);
        cbxProductos.add(cbxGaseosa);
        cbxProductos.add(cbxVino);
        cbxProductos.add(cbxJugo);
        
        return cbxProductos;
    }
    
    //RETORNA LA MESA Y SU LISTADO DE PRODUCTOS ASOCIADOS
    private Registro registroEnArray(int numeroMesa){
        Registro rg = new Registro();
        for (Registro rgTemp : registro) {
            if (rgTemp.getMesa().getNumeroMesa() == numeroMesa){
                rg = rgTemp;
            }
        }
        return rg;
    }
    
    private Registro registroEnArrayCliente(String nombreCliente){
        Registro rg = new Registro();
        for (Registro rgTemp : registro) {
            if (rgTemp.getCliente().getNombre().equalsIgnoreCase(nombreCliente)){
                rg = rgTemp;
            }
        }
        return rg;
    }
    
    //COMPRUEBA SI LA MESA EXISTE DENTRO DEL LISTADO DE MESAS
    private boolean mesaEnArray(int numeroMesa){
        
        boolean existe = false;
        for (Registro rgTemp : registro) {
            if (rgTemp.getMesa().getNumeroMesa() == numeroMesa){
                existe = true;
            }
        }
        return existe;
    }
    
    //RETORNA EL PRODUCTO SELECCIONADO DE LOS CHECKBOX DE PRODUCTOS
    private Producto obtenerProductoSeleccionado(JCheckBox cbxProductos) {
        Producto producto = new Producto();
        switch (cbxProductos.getText()) {

            case "Camarón":
                producto = new Producto("Camaron", 3990, "Entrada");
                break;
            case "Empanadas":
                producto = new Producto("Empanada", 2990, "Entrada");
                break;
            case "Palta Reina":
                producto = new Producto("Palta", 4990, "Entrada");
                break;
            case "Carne":
                producto = new Producto("Carne", 4990, "Principal");
                break;
            case "Cerdo":
                producto = new Producto("Cerdo", 4590, "Principal");
                break;
            case "Pescado":
                producto = new Producto("Pescado", 4190, "Principal");
                break;
            case "Arroz":
                producto = new Producto("Arroz", 1590, "Acompañamiento");
                break;
            case "Puré":
                producto = new Producto("Puré", 1490, "Acompañamiento");
                break;
            case "Ensalada":
                producto = new Producto("Ensalada", 1390, "Acompañamiento");
                break;
            case "Helado":
                producto = new Producto("Helado", 2590, "Postre");
                break;
            case "Tutifruti":
                producto = new Producto("Tutifruti", 990, "Postre");
                break;
            case "Leche Asada":
                producto = new Producto("Leche Asada", 1990, "Postre");
                break;
            case "Gaseosa":
                producto = new Producto("Gaseosa", 1100, "Bebida");
                break;
            case "Vino":
                producto = new Producto("Vino Tinto", 2490, "Bebida");
                break;
            case "Jugo":
                producto = new Producto("Jugo", 1990, "Bebida");
                break;
        }
        return producto;
    }
    
    private void btnAgregarPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPlatoActionPerformed

        //ASIGNA EL LISTADO DE BOTONES DE MESAS A UNA LISTA
        List<JToggleButton> botonesMesas = agregarBtn();
        
        //ASIGNA EL LISTADO DE CHECKBOX DE PRODUCTOS A UNA LISTA
        List<JCheckBox> cbxProductos = agregarCbx();
        
        //ITERA PARA CONOCER LA MESA SELECCIONADA
        if(clientes.isEmpty()){
            for (JToggleButton bMesa : botonesMesas) {
                if (bMesa.isSelected()) {

                    //SE UTILIZA EL METODO "mesaEnArray()" PARA COMPROBAR LA EXISTENCIA DE LA MESA Y LUEGO
                    //UTILIZARLA PARA AGREGAR LOS NUEVOS PRODUCTOS
                    if (mesaEnArray(Integer.parseInt(bMesa.getText()))) {
                        Registro rg = registroEnArray(Integer.parseInt(bMesa.getText()));
                        registro.remove(rg);
                        for (JCheckBox cbxProducto : cbxProductos) {
                            if (cbxProducto.isSelected()) {
                                rg.getProductos().add(obtenerProductoSeleccionado(cbxProducto));
                            }
                        }

                        //IMPRIME EN "txaPedido" LOS PRODUCTOS AGREGADOS
                        txaPedido.setText("====== Mesa " + bMesa.getText() + " ======\n\n");
                        for (Producto producto : rg.getProductos()) {
                            txaPedido.append(producto.getTipo() + ": " + producto.getNombre() + "\n");
                        }
                        registro.add(rg);

                        //INSTANCIA UN NUEVO OBJETO "Registro()" PARA AGREGAR LOS DATOS DE SUS
                        //VARIABLES (MESA Y PRODUCTOS)
                    } else {
                        Registro rg = new Registro();
                        Mesa mesaSeleccionada = new Mesa(Integer.parseInt(bMesa.getText()), true);
                        rg.setMesa(mesaSeleccionada);
                        for (JCheckBox cbxProducto : cbxProductos) {
                            if (cbxProducto.isSelected()) {
                                rg.getProductos().add(obtenerProductoSeleccionado(cbxProducto));
                            }
                        }
                        registro.add(rg);

                        //IMPRIME EN "txaPedido" LOS PRODUCTOS AGREGADOS
                        txaPedido.setText("====== Mesa " + bMesa.getText() + " ======\n\n");
                        for (Producto producto : rg.getProductos()) {
                            txaPedido.append(producto.getTipo() + ": " + producto.getNombre() + "\n");
                        }
                    }
                }
            }
        }else{
            txaPedido.setText("======= "+clientes.get(0).getNombre()+" =======\n\n");
                Registro rg = registroEnArrayCliente(clientes.get(0).getNombre());
                registro.remove(rg);
                rg.setCliente(clientes.get(0));

                    for (JCheckBox cbxProducto : cbxProductos) {
                        if (cbxProducto.isSelected()) {
                            rg.getProductos().add(obtenerProductoSeleccionado(cbxProducto));
                        }
                    }

                    for (Producto producto : rg.getProductos()) {
                        txaPedido.append(producto.getTipo() + ": " + producto.getNombre() + "\n");
                    }
                registro.add(rg);
        }
    }//GEN-LAST:event_btnAgregarPlatoActionPerformed
    
    
    public JToggleButton getBtnDelivery(){
        return btnDelivery;
    }
    
    private void btnDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeliveryActionPerformed

        datosDelivery d1 = new datosDelivery();
        d1.setVisible(true);
        btnDelivery.setEnabled(false);
        dispose();
    
        
    }//GEN-LAST:event_btnDeliveryActionPerformed

    private void btnPagoDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagoDeliveryActionPerformed
        //ACTIVA TEXTFIELD Y BOTON DE BUSQUEDA DE DELIVERY
        txtBusquedaDelivery.setEnabled(true);
        btnBuscarDelivery.setEnabled(true);
    }//GEN-LAST:event_btnPagoDeliveryActionPerformed

    private void btnPagoDeliveryFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnPagoDeliveryFocusLost
     
    }//GEN-LAST:event_btnPagoDeliveryFocusLost

    private void btnPagarMesa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarMesa1ActionPerformed
        // TODO add your handling code here:
        numMesa = 1;
        total = 0;
        txtBusquedaDelivery.setEnabled(false);
        btnBuscarDelivery.setEnabled(false);
        txaPagar.setText("======= Mesa 1 ======\n\n");
        for (Registro reg : registro) {
            if (reg.getMesa().getNumeroMesa() == numMesa){
                Producto prod = new Producto();
                for (Producto producto : reg.getProductos()) {
                    txaPagar.append(producto.getTipo()+ ": "+producto.getNombre()+ " = $"+producto.getPrecio()+"\n");
                }
                for (Producto producto : reg.getProductos()) {
                    total += producto.getPrecio();
                }
            }
        }
        txaPagar.append("\nTotal: $"+total);
        
    }//GEN-LAST:event_btnPagarMesa1ActionPerformed

    private void btnPagarMesa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarMesa2ActionPerformed
        // TODO add your handling code here:
        numMesa = 2;
        total = 0;
        txtBusquedaDelivery.setEnabled(false);
        btnBuscarDelivery.setEnabled(false);
        txaPagar.setText("======= Mesa 2 ======\n\n");
        for (Registro reg : registro) {
            if (reg.getMesa().getNumeroMesa() == numMesa){
                Producto prod = new Producto();
                for (Producto producto : reg.getProductos()) {
                    txaPagar.append(producto.getTipo()+ ": "+producto.getNombre()+ " = $"+producto.getPrecio()+"\n");
                }
                for (Producto producto : reg.getProductos()) {
                    total += producto.getPrecio();
                }
            }
        }
        txaPagar.append("\nTotal: $"+total);
        
    }//GEN-LAST:event_btnPagarMesa2ActionPerformed

    private void btnPagarMesa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarMesa3ActionPerformed
        // TODO add your handling code here:
        numMesa = 3;
        total = 0;
        txtBusquedaDelivery.setEnabled(false);
        btnBuscarDelivery.setEnabled(false);
        txaPagar.setText("======= Mesa 3 ======\n\n");
        for (Registro reg : registro) {
            if (reg.getMesa().getNumeroMesa() == numMesa){
                Producto prod = new Producto();
                for (Producto producto : reg.getProductos()) {
                    txaPagar.append(producto.getTipo()+ ": "+producto.getNombre()+ " = $"+producto.getPrecio()+"\n");
                }
                for (Producto producto : reg.getProductos()) {
                    total += producto.getPrecio();
                }
            }
        }
        txaPagar.append("\nTotal: $"+total);
    }//GEN-LAST:event_btnPagarMesa3ActionPerformed

    private void btnPagarMesa4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarMesa4ActionPerformed
        // TODO add your handling code here:
        numMesa = 4;
        total = 0;
        txtBusquedaDelivery.setEnabled(false);
        btnBuscarDelivery.setEnabled(false);
        txaPagar.setText("======= Mesa 4 ======\n\n");
        for (Registro reg : registro) {
            if (reg.getMesa().getNumeroMesa() == numMesa){
                Producto prod = new Producto();
                for (Producto producto : reg.getProductos()) {
                    txaPagar.append(producto.getTipo()+ ": "+producto.getNombre()+ " = $"+producto.getPrecio()+"\n");
                }
                for (Producto producto : reg.getProductos()) {
                    total += producto.getPrecio();
                }
            }
        }
        txaPagar.append("\nTotal: $"+total);
    }//GEN-LAST:event_btnPagarMesa4ActionPerformed

    private void btnPagarMesa5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarMesa5ActionPerformed
        // TODO add your handling code here:
        numMesa = 5;
        total = 0;
        txtBusquedaDelivery.setEnabled(false);
        btnBuscarDelivery.setEnabled(false);
        txaPagar.setText("======= Mesa 5 ======\n\n");
        for (Registro reg : registro) {
            if (reg.getMesa().getNumeroMesa() == numMesa){
                Producto prod = new Producto();
                for (Producto producto : reg.getProductos()) {
                    txaPagar.append(producto.getTipo()+ ": "+producto.getNombre()+ " = $"+producto.getPrecio()+"\n");
                }
                for (Producto producto : reg.getProductos()) {
                    total += producto.getPrecio();
                }
            }
        }
        txaPagar.append("\nTotal: $"+total);
    }//GEN-LAST:event_btnPagarMesa5ActionPerformed

    private void btnPagarMesa6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarMesa6ActionPerformed
        // TODO add your handling code here:
        numMesa = 6;
        total = 0;
        txtBusquedaDelivery.setEnabled(false);
        btnBuscarDelivery.setEnabled(false);
        txaPagar.setText("======= Mesa 6 ======\n\n");
        for (Registro reg : registro) {
            if (reg.getMesa().getNumeroMesa() == numMesa){
                Producto prod = new Producto();
                for (Producto producto : reg.getProductos()) {
                    txaPagar.append(producto.getTipo()+ ": "+producto.getNombre()+ " = $"+producto.getPrecio()+"\n");
                }
                for (Producto producto : reg.getProductos()) {
                    total += producto.getPrecio();
                }
            }
        }
        txaPagar.append("\nTotal: $"+total);
    }//GEN-LAST:event_btnPagarMesa6ActionPerformed

    private void btnAceptarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarPedidoActionPerformed
        txaPedido.append("***** PEDIDO INGRESADO *****");
        
        
        
    }//GEN-LAST:event_btnAceptarPedidoActionPerformed

    private void jPanel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel1FocusGained
   
    }//GEN-LAST:event_jPanel1FocusGained

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked

    }//GEN-LAST:event_jPanel1MouseClicked

    private void btnM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnM1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnM1ActionPerformed

    private void btnM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnM2ActionPerformed
        // TODO add your handling code here:
        numMesa = 2;
    }//GEN-LAST:event_btnM2ActionPerformed

    private void btnM3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnM3ActionPerformed
        // TODO add your handling code here:
        numMesa = 3;
    }//GEN-LAST:event_btnM3ActionPerformed

    private void btnM4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnM4ActionPerformed
        // TODO add your handling code here:
        numMesa = 4;
    }//GEN-LAST:event_btnM4ActionPerformed

    private void btnM5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnM5ActionPerformed
        // TODO add your handling code here:
        numMesa = 5;
    }//GEN-LAST:event_btnM5ActionPerformed

    private void btnM6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnM6ActionPerformed
        // TODO add your handling code here:
        numMesa = 6;
    }//GEN-LAST:event_btnM6ActionPerformed

    private void btnCancelarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPedidoActionPerformed
        //REMUEVE DATOS DE ARRAY DE PEDIDO
        for (Cliente cliente : clientes) {
            clientes.remove(cliente);
        }
            
        for (Registro reg : registro) {
            registro.remove(reg);
        }

        txaPedido.setText("");
        btnDelivery.setEnabled(true);
        btnM1.setEnabled(true);
        btnM2.setEnabled(true);
        btnM3.setEnabled(true);
        btnM4.setEnabled(true);
        btnM5.setEnabled(true);
        btnM6.setEnabled(true);
    }//GEN-LAST:event_btnCancelarPedidoActionPerformed

    private void btnBuscarDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDeliveryActionPerformed
        // BUSCA CLIENTE DE DELIVERY SEGÚN NOMBRE INGRESADO EN INPUT DE BUSQUEDA
        if (txtBusquedaDelivery.getText().equalsIgnoreCase(clientes.get(0).getNombre())){
            total = 0;
            txaPagar.setText("===============\nNombre Cliente: "+clientes.get(0).getNombre()+"\nDirección: "+clientes.get(0).getDireccion()+"\n===============\n\n");
            for (Registro reg : registro) {
                if (reg.getCliente().getNombre().equalsIgnoreCase(clientes.get(0).getNombre())){
                    Producto prod = new Producto();
                    for (Producto producto : reg.getProductos()) {
                        txaPagar.append(producto.getTipo()+ ": "+producto.getNombre()+ " = $"+producto.getPrecio()+"\n");
                    }
                    for (Producto producto : reg.getProductos()) {
                        total += producto.getPrecio();
                    }
                }
            }
        txaPagar.append("\nTotal: $"+total);
        }
    }//GEN-LAST:event_btnBuscarDeliveryActionPerformed

    private void btnPagarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarPedidoActionPerformed
        //CALCULA SI TOTAL ES MAYOR A CERO Y REALIZA TRANSACCIÓN DE PAGO
        if (total != 0){
            String mensaje = JOptionPane.showInputDialog(null, "Total $"+total);
            int mensajePago=Integer.parseInt(mensaje);  
            if(mensajePago >= total ){
                int vuelto=mensajePago-total;
                JOptionPane.showMessageDialog(null, "Vuelto: $"+vuelto+"\nTransacción realizada con éxito");
                txaPagar.setText("");
                for (Cliente cliente : clientes) {
                    clientes.remove(cliente);
                }
            
                for (Registro reg : registro) {
                    registro.remove(reg);
                }
            } else {
                JOptionPane.showMessageDialog(null, "pago incompleto");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ningún pedido ingresado");
        }
        
    }//GEN-LAST:event_btnPagarPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarPedido;
    private javax.swing.JButton btnAgregarPlato;
    private javax.swing.JButton btnBuscarDelivery;
    private javax.swing.JButton btnCancelarPedido;
    private javax.swing.JToggleButton btnDelivery;
    private javax.swing.JToggleButton btnM1;
    private javax.swing.JToggleButton btnM2;
    private javax.swing.JToggleButton btnM3;
    private javax.swing.JToggleButton btnM4;
    private javax.swing.JToggleButton btnM5;
    private javax.swing.JToggleButton btnM6;
    private javax.swing.JToggleButton btnPagarMesa1;
    private javax.swing.JToggleButton btnPagarMesa2;
    private javax.swing.JToggleButton btnPagarMesa3;
    private javax.swing.JToggleButton btnPagarMesa4;
    private javax.swing.JToggleButton btnPagarMesa5;
    private javax.swing.JToggleButton btnPagarMesa6;
    private javax.swing.JButton btnPagarPedido;
    private javax.swing.JToggleButton btnPagoDelivery;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JCheckBox cbxArroz;
    private javax.swing.JCheckBox cbxCamaron;
    private javax.swing.JCheckBox cbxCarne;
    private javax.swing.JCheckBox cbxCerdo;
    private javax.swing.JCheckBox cbxEmpanadas;
    private javax.swing.JCheckBox cbxEnsalada;
    private javax.swing.JCheckBox cbxGaseosa;
    private javax.swing.JCheckBox cbxHelado;
    private javax.swing.JCheckBox cbxJugo;
    private javax.swing.JCheckBox cbxLeche;
    private javax.swing.JCheckBox cbxPalta;
    private javax.swing.JCheckBox cbxPescado;
    private javax.swing.JCheckBox cbxPure;
    private javax.swing.JCheckBox cbxTuti;
    private javax.swing.JCheckBox cbxVino;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea txaPagar;
    private javax.swing.JTextArea txaPedido;
    private javax.swing.JTextField txtBusquedaDelivery;
    // End of variables declaration//GEN-END:variables

}
